version: '3'
services:
  api-app:
    build:
      context: ./api-app
    ports:
      - "5000:5000"

  client-app:
    build:
      context: ./client-app
    ports:
      - "3000:80" # Map to port 80 in the client app container

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api-app
      - client-app
